# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reTestProject
  pod 'SnapKit', '~> 5.6'
  pod 'SDWebImage', '~> 5.13'
  pod 'PromiseKit', '~> 6.18'
  pod 'Alamofire', '~> 5.6'

  target 'reTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reTestProjectUITests' do
    # Pods for testing
  end

end
